name: Zbuduj plik EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Zainstaluj biblioteki
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter requests "python-socketio[client]<5" "python-engineio<4" pystray Pillow pyinstaller
    - name: Kompiluj przez PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=logo.ico --add-data "logo.ico;." app.py
    - name: Wrzuć gotowy plik .exe jako Artefakt
      uses: actions/upload-artifact@v4
      with:
        name: TipplyBridge_Windows
        path: dist/app.exe
